### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by hanouel** [TheophileBuy/LicensePlateRecognition#1]
Hello,
I tried to run this code, I installed everything but it gives me these warnings and the code is not working:

WARNING:tensorflow:From C:\mypath\lib\site-packages\darkflow\net\build.py:15: The name tf.train.RMSPropOptimizer is deprecated. Please use tf.compat.v1.train.RMSPropOptimizer instead.

WARNING:tensorflow:From C:\mypath\lib\site-packages\darkflow\net\build.py:16: The name tf.train.AdadeltaOptimizer is deprecated. Please use tf.compat.v1.train.AdadeltaOptimizer instead.

WARNING:tensorflow:From C:\mypath\lib\site-packages\darkflow\net\build.py:17: The name tf.train.AdagradOptimizer is deprecated. Please use tf.compat.v1.train.AdagradOptimizer instead.

WARNING:tensorflow:From C:\mypath\lib\site-packages\darkflow\net\build.py:18: The name tf.train.AdagradDAOptimizer is deprecated. Please use tf.compat.v1.train.AdagradDAOptimizer instead.

WARNING:tensorflow:From C:\mypath\lib\site-packages\darkflow\net\build.py:19: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

Loading from .pb and .meta
WARNING:tensorflow:From C:\mypath\lib\site-packages\darkflow\net\build.py:81: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
WARNING:tensorflow:From C:\mypath\lib\site-packages\darkflow\net\build.py:82: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

can you gives a solution?

**Comment by hanouel** [comment]
the file yolo-plate.pb is not exist...

**Comment by biranchi2018** [comment]
> yolo-plate.pb

How to get the yolo-plate.pb then ?

**Comment by TheophileBuy** [comment]
Hi, sorry for the late answer.
I didn't realize that i can't put pb files in the repository. My bad.
You can now download Pb files at this link : https://drive.google.com/drive/folders/17gxw7tv7jy3KgJFhQiHX0IilYObFbIJp?usp=sharing

**Comment by hanouel** [comment]
Thank you, it works  now :)
