### ISSUE TITLE
No module named 'darkflow'

### ISSUE THREAD

**Issue by biranchi2018** [TheophileBuy/LicensePlateRecognition#2]
Traceback (most recent call last):
  File "finalPrototype.py", line 1, in <module>
    from darkflow.net.build import TFNet
ModuleNotFoundError: No module named 'darkflow'

Please mention the steps to build and include the required files and libraries.

**Comment by TheophileBuy** [comment]
Hi, sorry for the late answer,
From the darkflow documentation (https://github.com/thtrieu/darkflow), i think it would fix your issue :

Getting started
You can choose one of the following three ways to get started with darkflow.

    Just build the Cython extensions in place. NOTE: If installing this way you will have to use ./flow in the cloned darkflow directory instead of flow as darkflow is not installed globally.
    python3 setup.py build_ext --inplace
    Let pip install darkflow globally in dev mode (still globally accessible, but changes to the code immediately take effect)
    pip install -e .
    Install with pip globally
    pip install .
