### ISSUE TITLE
yolo.weights

### ISSUE THREAD

**Issue by arthurfortes** [TheophileBuy/LicensePlateRecognition#3]
Please, could you share the yolo.weights file?

I tried some weights in Yolo site, but not worked.

Regards.

**Comment by TheophileBuy** [comment]
Hi, i add the yolo.weights file i used to the drive folder :)

**Comment by hanouel** [comment]
Hi, for the yolo.weights do your use a standard file (trainined with 80 coco classes) or do you create a new weights file?
